using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;

class Program
{
    static void Main(string[] args)
    {
        QuestionFactory factory = new QuestionFactory();
        List<Question> question = new List<Question>
        {
        factory.Create(0, "Encapsulamento em Java é importante na Programação Orientada a Objetos.", true, "Lembre-se de que encapsulamento envolve a proteção dos dados da classe. Considere o papel dos modificadores de acesso e como eles ajudam a controlar a visibilidade e a integridade dos dados em uma classe.", 5, "POO", 1, "Java"),
        factory.Create(1, "Herança em Java é um conceito de reutilização de código.", true, "Herança permite que uma nova classe reutilize o código de uma classe existente, promovendo a reutilização e extensão do código.", 5, "POO", 1, "Java"),
        factory.Create(2, "Uma classe abstrata e uma interface em Java têm diferenças em relação à implementação de métodos.", true, "Classes abstratas podem ter métodos implementados, enquanto interfaces só definem métodos sem implementação. Use interfaces para definir contratos de comportamento.", 5, "POO", 1, "Java"),
        factory.Create(3, "Construtores em Java têm o propósito de inicializar objetos.", true, "Construtores são métodos especiais que são executados quando uma instância de uma classe é criada, garantindo que o objeto esteja corretamente inicializado.", 5, "POO", 1, "Java"),
        factory.Create(4, "Polimorfismo é aplicado em Java para permitir que objetos de diferentes classes sejam tratados de maneira uniforme.", true, "Polimorfismo permite que um objeto de uma subclasse seja tratado como um objeto da superclasse, aumentando a flexibilidade do código.", 5, "POO", 1, "Java"),
        factory.Create(5,"Classes Wrapper (Integer, Float, Double...) em Java são usadas para representar tipos primitivos como objetos.", true, "Classes Wrapper encapsulam tipos primitivos em objetos, permitindo que sejam usados onde objetos são necessários, como em coleções.", 5, "Geral", 1, "Java"),
        factory.Create(6, "Exceções em Java são usadas para lidar com erros e situações excepcionais.", true, "Exceções permitem que o programa capture e trate situações inesperadas de maneira controlada, melhorando a robustez e a confiabilidade do código.", 5, "Geral", 1, "Java"),
        factory.Create(7, "Objetos não são instâncias de classes em Java.", false, "Em Java, objetos são instâncias de classes, o que significa que eles são criados a partir de classes e podem utilizar seus métodos e atributos.", 5, "Geral", 1, "Java"),
        factory.Create(8, "Classes internas (inner classes) em Java não têm muita utilidade pois não são usadas em muitos cenários, pois não oferecem benefícios em relação a classes normais.", false, "Classes internas podem ser úteis em situações onde uma classe é fortemente ligada a outra, permitindo um encapsulamento mais eficiente e acesso direto a membros privados da classe externa.", 5, "POO", 1, "Java"),
        factory.Create(9, "Um método estático (static method) em Java está estritamente associado a uma instância específica da classe e não pode ser chamado diretamente pela classe em si.", false, "Métodos estáticos são associados à classe em si e não a instâncias específicas. Eles podem ser chamados diretamente pela classe.", 5, "Geral", 1, "Java"),
        factory.Create(10, "Scrum é uma metodologia ágil e difere de outras abordagens ágeis, como o Kanban, em vários aspectos.", true, "Scrum é um framework ágil que foca em ciclos de trabalho curtos e regulares, chamados sprints, e tem um conjunto definido de papéis e eventos, enquanto Kanban é mais focado em um fluxo contínuo de trabalho.", 5, "Geral", 1, "Geral"),
        factory.Create(11, "O Manifesto Ágil tem valores, e é possível explicar cada um deles.", true, "O Manifesto Ágil possui quatro valores principais que guiam as práticas ágeis: indivíduos e interações, software funcionando, colaboração com o cliente, e resposta a mudanças.", 5, "Geral", 1, "Geral"),
        factory.Create(12, "Uma sprint em Scrum tem um propósito definido.", true, "Cada sprint em Scrum tem o objetivo de entregar um incremento do produto que seja potencialmente utilizável, promovendo o progresso contínuo.", 5, "Geral", 1, "Geral"),
        factory.Create(13, "O Scrum Master facilita o processo em um time Scrum e desempenha um papel específico.", true, "O Scrum Master ajuda o time a seguir as práticas de Scrum, removendo impedimentos e garantindo que o processo seja eficiente.", 5, "Geral", 1, "Geral"),
        factory.Create(14, "A revisão de sprint em Scrum não tem um objetivo claro.", false, "A revisão de sprint tem como objetivo apresentar o trabalho realizado, permitindo que o time e as partes interessadas discutam o que foi feito e planejem os próximos passos.", 5, "Geral", 1, "Geral"),
        factory.Create(15, "Na reunião de planejamento da sprint em Scrum, ocorre um processo essencial em que a equipe Scrum colaborativamente estabelece os objetivos e o escopo da próxima sprint.", true, "O planejamento da sprint é crucial para definir o que será feito na próxima sprint, garantindo alinhamento e foco para a equipe.", 5, "Geral", 1, "Geral"),
        factory.Create(16, "Lean Thinking não está relacionado às práticas ágeis.", false, "Lean Thinking compartilha princípios com as práticas ágeis, como a eliminação de desperdícios e a melhoria contínua, sendo muitas vezes integrado às abordagens ágeis.", 5, "Geral", 1, "Geral"),
        factory.Create(17, "O DoD (Definition of Done) em Scrum não tem uma importância definida.", false, "O DoD é essencial em Scrum, pois define claramente quando um item de backlog está completo e pronto para ser considerado como terminado, garantindo a qualidade e a integridade do trabalho.", 5, "Scrum", 1, "Geral"),
        factory.Create(18, "Continuous Integration se encaixa nas metodologias ágeis.", true, "Continuous Integration (Integração Contínua) é uma prática que se alinha bem com metodologias ágeis, permitindo que o código seja integrado e testado frequentemente para garantir qualidade e detectar problemas mais cedo.", 5, "Geral", 1, "Geral"),
        factory.Create(19, "A retrospectiva de sprint em Scrum tem uma finalidade específica.", true, "A retrospectiva de sprint é um evento crítico em Scrum que permite ao time refletir sobre o trabalho realizado e identificar melhorias para o próximo sprint, promovendo o aprimoramento contínuo.", 5, "Scrum", 1, "Geral"),
        factory.Create(20, "Em Java, a herança múltipla é permitida para evitar duplicação de código.", false, "Java não permite herança múltipla para evitar complexidades e problemas como a ambiguidade de métodos. Em vez disso, utiliza interfaces para permitir a implementação de múltiplos comportamentos.", 5, "POO", 1, "Java"),
        factory.Create(21, "Em Scrum, os membros da equipe de desenvolvimento não têm influência sobre as estimativas de esforço das histórias de usuário.", false, "A equipe de desenvolvimento participa ativamente das estimativas de esforço das histórias de usuário para garantir que as estimativas sejam realistas e baseadas no conhecimento coletivo.", 5, "Geral", 1, "Geral"),
        factory.Create(22, "Em Java, todas as variáveis não são declaradas com um tipo específico.", false, "Em Java, todas as variáveis devem ser declaradas com um tipo específico, pois Java é uma linguagem de programação fortemente tipada.", 5, "Java", 1, "Java"),
        factory.Create(23, "Em Scrum, o Product Owner não desempenha um papel ativo na priorização do backlog do produto.", false, "O Product Owner é responsável por priorizar o backlog do produto para maximizar o valor entregue pelo time.", 5, "Geral", 1, "Geral"),
        factory.Create(24, "Em Java, métodos abstratos podem ter implementações padrão.", false, "Métodos abstratos em Java não podem ter implementações padrão. Eles devem ser implementados pelas subclasses.", 5, "Java", 1, "Java"),
        factory.Create(25, "No Manifesto Ágil, a ênfase é colocada na documentação detalhada e abrangente.", false, "O Manifesto Ágil prioriza a comunicação face a face e a colaboração, em vez de documentação extensiva.", 5, "Geral", 1, "Geral"),
        factory.Create(26, "Em Scrum, a retrospectiva de sprint ocorre antes da revisão de sprint.", false, "A retrospectiva de sprint ocorre após a revisão de sprint e é o momento para refletir sobre o trabalho realizado e planejar melhorias.", 5, "Geral", 1, "Geral"),
        factory.Create(27, "Em Java, métodos finais podem ser sobrescritos por subclasses.", false, "Métodos finais em Java não podem ser sobrescritos por subclasses. A palavra-chave `final` impede a sobrescrição.", 5, "Java", 1, "Java"),
        factory.Create(28, "Em Scrum, o Scrum Master é responsável pela definição do backlog do produto.", false, "O Scrum Master facilita o processo Scrum, mas a definição e priorização do backlog do produto é responsabilidade do Product Owner.", 5, "Geral", 1, "Geral"),
        factory.Create(29, "O SQL é uma linguagem de programação usada para gerenciar bancos de dados.", false, "SQL (Structured Query Language) é uma linguagem de consulta usada para gerenciar e manipular dados em bancos de dados, mas não é considerada uma linguagem de programação no sentido tradicional.", 5, "Geral", 1, "Geral"),
        factory.Create(31, "O SQL é uma linguagem de alto nível que permite aos desenvolvedores interagir com bancos de dados de forma fácil e eficaz.", true, "SQL é uma linguagem de alto nível projetada para facilitar a interação com bancos de dados e manipulação de dados de forma eficaz.", 5, "Geral", 1, "SQL"),
        factory.Create(32, "No SQL, a cláusula SELECT é usada para recuperar dados de uma tabela.", true, "A cláusula SELECT em SQL é usada para consultar e recuperar dados armazenados em tabelas de um banco de dados.", 5, "Geral", 1, "SQL"),
        factory.Create(33, "O SQL é uma linguagem padronizada, o que significa que as instruções SQL são as mesmas em todos os sistemas de gerenciamento de banco de dados (SGBDs).", true, "SQL é uma linguagem padrão que é implementada de forma semelhante em diferentes sistemas de gerenciamento de banco de dados, embora possa haver variações.", 5, "Geral", 1, "SQL"),
        factory.Create(34, "A cláusula WHERE é usada em SQL para filtrar os registros que atendem a uma condição específica.", true, "A cláusula WHERE é utilizada em SQL para especificar condições que os registros devem atender para serem incluídos nos resultados da consulta.", 5, "Geral", 1, "SQL"),
        factory.Create(35, "O SQL permite a criação, atualização e exclusão de registros em um banco de dados usando as instruções INSERT, UPDATE e DELETE.", true, "SQL permite manipular dados em um banco de dados através das instruções INSERT, UPDATE e DELETE, que adicionam, modificam e removem registros, respectivamente.", 5, "Geral", 1, "SQL"),
        factory.Create(36, "A cláusula VIEW é usada em SQL para combinar dados de duas ou mais tabelas relacionadas.", false, "A cláusula VIEW é usada para criar uma visão que combina dados de várias tabelas. A instrução correta para combinar dados é JOIN.", 5, "Geral", 1, "SQL"),
        factory.Create(37, "A linguagem SQL não oferece suporte à criação de procedimentos armazenados, funções e gatilhos.", false, "SQL suporta a criação de procedimentos armazenados, funções e gatilhos para gerenciar e automatizar operações em um banco de dados.", 5, "Geral", 1, "SQL"),
        factory.Create(38, "A instrução SQL START TABLE é usada para criar uma nova tabela em um banco de dados.", false, "A instrução correta para criar uma nova tabela é CREATE TABLE. START TABLE não é uma instrução SQL válida.", 5, "Geral", 1, "SQL"),
        factory.Create(39, "No SQL, a cláusula SELECT é usada para mover dados de uma tabela.", false, "A cláusula SELECT é usada para consultar e recuperar dados, não para mover dados entre tabelas. A movimentação de dados pode ser feita com operações de INSERT ou UPDATE.", 5, "Geral", 1, "SQL"),
        factory.Create(40, "O SQL é amplamente utilizado em sistemas de gerenciamento de banco de dados não relacionais, como MySQL, PostgreSQL e Oracle.", false, "SQL é amplamente utilizado em sistemas de gerenciamento de banco de dados relacionais. MySQL, PostgreSQL e Oracle são SGBDs relacionais que utilizam SQL. Bancos de dados não relacionais usam outras linguagens.", 5, "Geral", 1, "SQL"),
        factory.Create(41, "Em lógica de programação, um algoritmo é uma sequência finita de instruções que descreve um processo de resolução de um problema.", true, "Um algoritmo é uma série ade passos claros e definidos para resolver um problema específico, garantindo que a solução seja alcançada de forma ordenada.", 5, "Geral", 1, "Lógica de Programação"),
        factory.Create(42, "O termo LOOP refere-se a uma estrutura de controle que permite que um conjunto de instruções seja executado repetidamente enquanto uma condição for verdadeira.", true, "LOOP é uma estrutura fundamental de controle que permite a repetição de um bloco de código enquanto uma condição específica for satisfeita.", 5, "Geral", 1, "Lógica de Programação"),
        factory.Create(43, "A lógica de programação é independente de linguagens de programação específicas e se aplica a qualquer linguagem.", true, "A lógica de programação refere-se aos princípios e conceitos que são universais e aplicáveis em qualquer linguagem de programação.", 5, "Geral", 1, "Lógica de Programação"),
        factory.Create(44, "Um operador lógico AND retorna verdadeiro se um das condições envolvidas forem verdadeiras.", false, "O operador lógico AND retorna verdadeiro somente se todas as condições envolvidas forem verdadeiras. Se qualquer uma das condições for falsa, o resultado será falso.", 5, "Geral", 1, "Lógica de Programação"),
        factory.Create(45, "Em lógica de programação, um operador de igualdade é representado por ==, e um único sinal = é usado para atribuição de valores a variáveis.", true, "O operador de igualdade == é usado para comparar valores, enquanto = é usado para atribuição de valores às variáveis.", 5, "Geral", 1, "Lógica de Programação"),
        factory.Create(46, "A estrutura de controle SWITCH é frequentemente usada para substituir várias instruções IF quando se deseja avaliar múltiplas condições.", true, "A estrutura SWITCH permite a avaliação de múltiplas condições de forma mais clara e organizada do que usar várias instruções IF aninhadas.", 5, "Geral", 1, "Lógica de Programação"),
        factory.Create(47, "Em lógica de programação, uma matriz (array) é uma estrutura de dados que armazena uma coleção de elementos de tipos diferentes.", false, "Uma matriz (array) armazena elementos do mesmo tipo em uma coleção ordenada. Para armazenar elementos de tipos diferentes, geralmente se usa uma estrutura de dados mais flexível, como uma lista de objetos.", 5, "Geral", 1, "Lógica de Programação"),
        factory.Create(48, "Um algoritmo eficiente é aquele que consome a maior quantidade de recursos computacionais possível para resolver um problema.", false, "Um algoritmo eficiente é aquele que consome o menor número possível de recursos computacionais, como tempo e memória, para resolver um problema.", 5, "Geral", 1, "Lógica de Programação"),
        factory.Create(49, "O algoritmo conhecido com Bubble Sort é o mais conhecido e utilizado devido a sua alta capacidade de ordenar dados de maneira rápida e eficiente.", false, "O Bubble Sort é um algoritmo de ordenação simples, mas geralmente ineficiente em termos de tempo de execução, especialmente para grandes conjuntos de dados. Existem algoritmos mais eficientes, como Quick Sort e Merge Sort.", 5, "Geral", 1, "Lógica de Programação"),
        factory.Create(50, "Em lógica de programação, a recursão é um conceito onde uma função chama a varias outras funções para resolver um problema, geralmente dividindo-o em subproblemas menores.", false, "Recursão é um conceito onde uma função se chama a si mesma para resolver subproblemas menores. Não envolve chamar várias outras funções, mas sim a própria função para dividir e conquistar o problema.", 5, "Geral", 1, "Lógica de Programação"),
        factory.Create(51, "A World Wide Web (WWW) e a internet são a mesma coisa.", false, "A World Wide Web (WWW) é um serviço acessado através da internet, mas a internet é a infraestrutura global de redes que suporta a WWW e outros serviços.", 5, "Geral", 1, "Geral"),
        factory.Create(52, "HTTPS é um protocolo de transferência de hipertexto seguro usado para criptografar a comunicação entre o navegador e o servidor web.", true, "HTTPS é uma versão segura do HTTP que utiliza criptografia para proteger a comunicação entre o navegador e o servidor.", 5, "Geral", 1, "Geral"),
        factory.Create(53, "CSS (Cascading Style Sheets) é usado para estilizar e formatar elementos HTML em uma página web.", true, "CSS é uma linguagem de estilo usada para definir a aparência e o layout dos elementos HTML em uma página web.", 5, "Geral", 1, "Geral"),
        factory.Create(54, "JavaScript é uma linguagem de programação frequentemente usada para adicionar interatividade e dinamismo a páginas web.", true, "JavaScript é amplamente utilizado para criar interatividade e dinamismo em páginas web, permitindo a manipulação de elementos HTML e CSS.", 5, "Geral", 1, "Geral"),
        factory.Create(55, "Um 'COOKIE' é um pequeno arquivo de texto armazenado no navegador do usuário e frequentemente usado para rastrear informações de sessão em um site.", true, "Cookies são usados para armazenar informações sobre o usuário e suas preferências, ajudando a manter a sessão ativa e personalizar a experiência.", 5, "Geral", 1, "Geral"),
        factory.Create(56, "A sigla 'URL' significa 'Uniform Resource Locator' e é usada para identificar o endereço de um recurso na web.", true, "URL é o endereço usado para localizar e acessar recursos na web, como páginas e arquivos.", 5, "Geral", 1, "Geral"),
        factory.Create(57, "Um servidor web é um software que fornece páginas e recursos da web para navegadores da web.", true, "Servidores web são responsáveis por armazenar, processar e entregar páginas da web e outros recursos para os navegadores dos usuários.", 5, "Geral", 1, "Geral"),
        factory.Create(58, "SEO (Search Engine Optimization) é um conjunto de técnicas usadas para melhorar a velocidade de um site.", false, "SEO é uma prática para melhorar a visibilidade e a classificação de um site nos motores de busca, não necessariamente para aumentar a velocidade do site.", 5, "Geral", 1, "Geral"),
        factory.Create(59, "O protocolo HTTPS (Hypertext Transfer Protocol) é usado para a transferência de dados na web e é baseado no modelo cliente-servidor.", false, "HTTPS é baseado no HTTP e adiciona uma camada de segurança, mas o modelo cliente-servidor é uma característica geral da web, não exclusiva do HTTPS.", 5, "Geral", 1, "Geral"),
        factory.Create(60, "Uma API (Interface de Programação de Aplicativos) é um conjunto de regras e protocolos que impede que diferentes softwares se comuniquem e compartilhem dados ou funcionalidades.", false, "Uma API permite que diferentes softwares se comuniquem e compartilhem dados ou funcionalidades, facilitando a integração entre sistemas.", 5, "Geral", 1, "Geral"),
        factory.Create(61, "Uma variável é um local de armazenamento que pode conter um valor ou uma referência a um valor.", true, "Uma variável é usada para armazenar dados, podendo conter valores diretos ou referências a valores em memória.", 5, "Geral", 1, "Geral"),
        factory.Create(62, "O operador lógico 'OR' retorna verdadeiro se pelo menos uma das condições envolvidas for verdadeira.", true, "O operador 'OR' (ou || em muitas linguagens) retorna verdadeiro se pelo menos uma das condições for verdadeira.", 5, "Geral", 1, "Geral"),
        factory.Create(63, "A declaração 'switch' é usada para avaliar múltiplas condições em uma estrutura de controle condicional.", true, "A declaração 'switch' permite testar uma variável contra vários valores possíveis, facilitando a escolha entre múltiplas opções.", 5, "Geral", 1, "Geral"),
        factory.Create(64, "O operador 'NOT' (ou '!' em algumas linguagens) inverte o valor lógico de uma expressão, tornando verdadeiro em falso e vice-versa.", true, "O operador 'NOT' inverte o valor lógico de uma expressão booleana, transformando verdadeiro em falso e vice-versa.", 5, "Geral", 1, "Geral"),
        factory.Create(65, "A complexidade de tempo de um algoritmo descreve a quantidade de recursos de computação necessária para executá-lo.", true, "A complexidade de tempo mede a eficiência de um algoritmo em termos do tempo necessário para sua execução.", 5, "Geral", 1, "Geral"),
        factory.Create(66, "Em lógica de programação, a declaração 'while' é uma estrutura de controle usada para criar loops com um contador controlado por uma variável.", false, "'While' é usada para criar loops baseados em uma condição que é avaliada antes de cada iteração, não necessariamente com um contador controlado por uma variável.", 5, "Geral", 1, "Geral"),
        factory.Create(67, "A análise de algoritmos é uma disciplina que se concentra em avaliar o desempenho e a eficiência de algoritmos em termos de tempo e espaço.", true, "A análise de algoritmos avalia o desempenho de algoritmos, focando em como o tempo e o espaço de execução variam com o tamanho dos dados.", 5, "Geral", 1, "Geral"),
        factory.Create(68, "Um 'loop infinito' é um tipo de loop que tem uma condição de parada clara e continua a ser executado indefinidamente.", false, "Um loop infinito é caracterizado por não ter uma condição de parada clara, resultando em execução indefinida.", 5, "Geral", 1, "Geral"),
        factory.Create(69, "Em um modelo de banco de dados relacional, uma chave primaria é usada para estabelecer relacionamentos entre tabelas.", false, "A chave primária é usada para identificar de forma única cada linha em uma tabela, enquanto as chaves estrangeiras estabelecem relacionamentos entre tabelas.", 5, "Geral", 1, "Geral"),
        factory.Create(70, "No modelo relacional, as visões (views) são usadas para criar representações virtuais de dados, permitindo que os usuários vejam os dados de maneira personalizada, alterando a estrutura das tabelas existentes.", false, "Visões são representações virtuais de dados que permitem consultas personalizadas sem alterar a estrutura das tabelas existentes.", 5, "Geral", 1, "Geral")
        };
        var dataToSerialize = new { Questions = question };

        JsonSerializerOptions options = new JsonSerializerOptions
        {
            WriteIndented = true,
            Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping
        };

        string json = JsonSerializer.Serialize(dataToSerialize, options);

        string outputFilePath = "questions.json";
        File.WriteAllText(outputFilePath, json);

        Console.WriteLine("Perguntas salvas no arquivo JSON:");
        Console.WriteLine(json);
    }
}